// <auto-generated />
using Basket_Store_MS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Basket_Store_MS.Migrations
{
    [DbContext(typeof(BasketStoreDBContext))]
    partial class BasketStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Basket_Store_MS.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentType = 0,
                            State = "Delivered",
                            TotalCost = 50.600000000000001
                        },
                        new
                        {
                            Id = 2,
                            PaymentType = 0,
                            State = "Open",
                            TotalCost = 40.219999999999999
                        });
                });

            modelBuilder.Entity("Basket_Store_MS.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = 2
                        });
                });

            modelBuilder.Entity("Basket_Store_MS.Models.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FeedBackDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductsId");

                    b.ToTable("FeedBacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeedBackDescription = "Beauty",
                            ProductsId = 1,
                            Rating = 40.299999999999997
                        },
                        new
                        {
                            Id = 2,
                            FeedBackDescription = "Clothes",
                            ProductsId = 2,
                            Rating = 150.40000000000001
                        });
                });

            modelBuilder.Entity("Basket_Store_MS.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTypes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 0,
                            PaymentTypes = "Visa"
                        },
                        new
                        {
                            Id = 2,
                            CartId = 0,
                            PaymentTypes = "Master Card"
                        });
                });

            modelBuilder.Entity("Basket_Store_MS.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Discount")
                        .HasColumnType("bit");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Discount = true,
                            InStock = 150,
                            Name = "Eyeliner",
                            Price = 10.0,
                            ProductDescription = "Test"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Discount = false,
                            InStock = 100,
                            Name = "Trousers",
                            Price = 20.0,
                            ProductDescription = "Test2"
                        });
                });

            modelBuilder.Entity("Basket_Store_MS.Models.FeedBack", b =>
                {
                    b.HasOne("Basket_Store_MS.Models.Products", null)
                        .WithMany("FeedBack")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Basket_Store_MS.Models.PaymentType", b =>
                {
                    b.HasOne("Basket_Store_MS.Models.Cart", "Cart")
                        .WithOne("PaymentTypes")
                        .HasForeignKey("Basket_Store_MS.Models.PaymentType", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Basket_Store_MS.Models.Products", b =>
                {
                    b.HasOne("Basket_Store_MS.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Basket_Store_MS.Models.Cart", b =>
                {
                    b.Navigation("PaymentTypes");
                });

            modelBuilder.Entity("Basket_Store_MS.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Basket_Store_MS.Models.Products", b =>
                {
                    b.Navigation("FeedBack");
                });
#pragma warning restore 612, 618
        }
    }
}
